kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-api-config
  namespace: vik
  labels:
    app: fake-weather
    service: sample-api
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-api
  namespace: vik
  labels:
    app: fake-weather
    service: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sample-api
  template:
    metadata:
      labels:
        app: fake-weather
        service: sample-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sample-api-app-id"
        dapr.io/app-port: "5000"
        dapr.io/app-ssl: "false"
        dapr.io/log-level: "debug"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
        dapr.io/app-protocol: "http"
        dapr.io/sidecar-liveness-probe-delay-seconds: "30"
        dapr.io/sidecar-readiness-probe-delay-seconds: "30"
    spec:
      containers:
        - name: sample-api
          image: sampleapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: sample-api-config


---

apiVersion: v1
kind: Service
metadata:
  name: sample-api
  namespace: vik
  labels:
    app: fake-weather
    service: sample-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: api-http
  selector:
    service: sample-api