apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: vik
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.vik.svc.cluster.local:6379
  - name: enableTLS
    value: false
  - name: actorStateStore
    value: true